---
# playbook.yml
# ansible-playbook playbook.yml

- name: Create Jenkins multiple docker images
  hosts: localhost
  become: true
  gather_facts: no

  vars:
    # Jenkins für Team 1
    dev_vol_1: "jenkins-1-home-dev"
    prod_vol_1: "jenkins-1-home-prod"
    dev_name_1: "jenkins-1-dev"
    prod_name_1: "jenkins-1-prod"
    prod_port_1: "9090"
    jnlp_port_1: "50001"
    # Jenkins für Team 2
    dev_vol_2: "jenkins-home-dev"
    prod_vol_2: "jenkins-home-prod"
    dev_name_2: "jenkins_dev"
    prod_name_2: "jenkins_prod"
    prod_port_2: "9091"
    jnlp_port_2: "50002"

  tasks:
  - name: "Install nginx"
    apt:
      name: nginx
      state: present

  - name: "Install nginx Configuration"
    template:
      src: jenkins.conf.j2
      dest: /etc/nginx/sites-available/jenkins
      owner: root
      group: root
      mode: "0644"

  - name: "Enable Jenkins Nginx Proxy"
    file:
      src: /etc/nginx/sites-available/jenkins
      dest: /etc/nginx/sites-enabled/jenkins
      owner: root
      group: root
      state: link

  - name: "Create jenkins-home-1-prod Volume"
    community.general.docker_volume:
      name: "{{ prod_vol_1 }}"

  - name: "Create groovy.init.d directory"
    shell: "docker exec {{ prod_vol_1 }} mkdir -p /init.groovy.d"

  - name: "Copy jenkins-set-url-and-email.groovy into data-volume"
    shell: "docker cp jenkins-set-url-and-email.groovy {{ prod_vol_1 }}:/init.groovy.d/jenkins-set-url-and-email.groovy"

  - name: "Create jenkins-home-2-prod Volume"
    community.general.docker_volume:
      name: "{{ prod_vol_2 }}"

  - name: "Create Jenkins 1 Prod Container"
    community.general.docker_container:
      name: "{{ prod_name_1 }}"
      image: jenkins/jenkins:lts
      volumes:
        - "{{ prod_vol_1 }}:/var/jenkins_home"
      ports:
        # Publish container port 8080 as host port 9090
        - "{{ prod_port_1 }}:8080"
        # Publish container port 50000 as host port 50001
        - "{{ jnlp_port_1 }}:50000"
      env:
        JENKINS_OPTS: "--prefix=/node1" 
        JAVA_OPTS: "-Dhudson.footerURL=http://18.193.172.241/node1 -Djenkins.install.runSetupWizard=false"

  - name: "Create Jenkins 2 Prod Container"
    community.general.docker_container:
      name: "{{ prod_name_2 }}"
      image: jenkins/jenkins:lts
      volumes:
        - "{{ prod_vol_2 }}:/var/jenkins_home"
      ports:
        # Publish container port 8080 as host port 9091
        - "{{ prod_port_2 }}:8080"
        # Publish container port 50000 as host port 50002
        - "{{ jnlp_port_2 }}:50000"
      env:
        JENKINS_OPTS: "--prefix=/node2"
        JAVA_OPTS: "-Dhudson.footerURL=http://18.193.172.241/node2 -Djenkins.install.runSetupWizard=false"
  
  - name: "Remove Jenkins Prod 1 Container"
    community.general.docker_container:
      name: "{{ prod_name_1 }}"
      state: absent
    tags: [ 'never', 'destroy' ]

  - name: "Remove Jenkins Prod 2 Container"
    community.general.docker_container:
      name: "{{ prod_name_2 }}"
      state: absent
    tags: [ 'never', 'destroy' ]

  - name: "Remove jenkins-home-1-prod Volume" 
    community.general.docker_volume:
      name: "{{ prod_vol_1 }}" 
      state: absent
    tags: [ 'never', 'destroy' ]

  - name: "Remove jenkins-home-2-prod Volume" 
    community.general.docker_volume:
      name: "{{ prod_vol_2 }}" 
      state: absent
    tags: [ 'never', 'destroy' ]
